theme: null 
markdown: kramdown

collections:
  ai_insights:
    output: true
    permalink: /AI-Insights/:slug/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "ai_insights"
    values:
      repo: "AI-Insights"